// <auto-generated />
namespace Survey.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validation));
        
        string IMigrationMetadata.Id
        {
            get { return "201404090459106_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
